### ISSUE TITLE
Migrations are of old version

### ISSUE THREAD

**Issue by duhjent** [duhjent/MediAR-backend#1]
Current migrations assume o2m relationship between user and course. The entities description were updated accordingly, but migrations are the same.

**Comment by duhjent** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Оновлення міграцій](https://trello.com/c/IsuU5CeZ/46-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BC%D1%96%D0%B3%D1%80%D0%B0%D1%86%D1%96%D0%B9)

**Comment by rvovck** [comment]
Fixed in last hotfix
